gtkmm-CI-Example: test/math_test.cpp File Reference
math_test.cpp File Reference
#include <gtest/gtest.h>
#include "math/math.h"
Functions
TEST (MathAddTest, PositiveNum)
TEST (MathAddTest, ZeroB)
TEST (MathSubTest, PositiveNum)
TEST (MathSubTest, ZeroB)
TEST (MathMulTest, PositiveNum)
TEST (MathMulTest, ZeroB)
Function Documentation
TEST() [1/6]
TEST (MathAddTest , PositiveNum)
Definition at line 4 of file math_test.cpp.
{
    EXPECT_EQ(2, math::add(1, 1));
    EXPECT_EQ(10, math::add(2, 8));
    EXPECT_EQ(100, math::add(50, 50));
}
References math::add().
TEST() [2/6]
TEST (MathAddTest , ZeroB)
Definition at line 10 of file math_test.cpp.
{
    EXPECT_EQ(1, math::add(1, 0));
    EXPECT_EQ(10, math::add(10, 0));
    EXPECT_EQ(100, math::add(100, 0));
}
References math::add().
TEST() [3/6]
TEST (MathMulTest , PositiveNum)
Definition at line 28 of file math_test.cpp.
{
    EXPECT_EQ(1, math::mul(1, 1));
    EXPECT_EQ(16, math::mul(2, 8));
    EXPECT_EQ(1500, math::mul(150, 10));
}
References math::mul().
TEST() [4/6]
TEST (MathMulTest , ZeroB)
Definition at line 34 of file math_test.cpp.
{
    EXPECT_EQ(0, math::mul(1, 0));
    EXPECT_EQ(0, math::mul(10, 0));
    EXPECT_EQ(0, math::mul(100, 0));
}
References math::mul().
TEST() [5/6]
TEST (MathSubTest , PositiveNum)
Definition at line 16 of file math_test.cpp.
{
    EXPECT_EQ(0, math::sub(1, 1));
    EXPECT_EQ(-6, math::sub(2, 8));
    EXPECT_EQ(100, math::sub(150, 50));
}
References math::sub().
TEST() [6/6]
TEST (MathSubTest , ZeroB)
Definition at line 22 of file math_test.cpp.
{
    EXPECT_EQ(1, math::sub(1, 0));
    EXPECT_EQ(10, math::sub(10, 0));
    EXPECT_EQ(100, math::sub(100, 0));
}
References math::sub().