name: function_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install libgtkmm-3.0
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make test
    - name: Run Test
      run: cd build && ./test/test
